- name: variables in ansible
  hosts: mongodb
  # this is play level variables, map
  vars:
    COURS: devops
    TRAINER: shiva sir
    DURATION: 110hours
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello I am learning ansible" 
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello I am learning {{COURSE}},Trainer is {{TRAINER}},Duration is {{DURATION}}"