- name: variables from files
  hosts: localhost #Managing the  ansible aserver it self
  vars_files:
  - variables.yaml
  tasks:
  - name: 
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}},trainer name is {{TRAINER}} and Duration is {{DURATION}}"