# we given the same variable name 'NAME' from play,file,prompt,args,task and given the print and checking the which vlue will print

- name: testing vaiables precedence
  hosts: mongodb
  # vars: #variables from play
  #   NAME: chandu-play
  #vars_files: #variables from file
  #- variables.yaml 
  # vars_prompt: #variables from prompt
  # - name: NAME
  #   prompt: please enter trainer name
  #   private: false      
  tasks:  #variables from task
  - name: variables ata task levell
    #vars:
     #NAME: chandu-task
    ansible.builtin.debug:
      msg: "Trainer name is {{NAME}}"    #variables from args 

   # 1. first preference is command line args variables
   # 2. second presedence is task variables  
   # 3. 3rd precedense is file variables
   #4. prompt variables
   #5.play levell variable
   #6 . invontary variables
   #7. Roles variables

   
#- name: testing vaiable sprecedence
#  hosts: mongodb
#  vars: #variables from play
#    NAME: chandu-play
#  vars_files: #variables from file
#  - variables.yaml 
#  vars_prompt: #variables from prompt
#  - name: NAME
#    prompt: please enter trainer name
#    private: false      
#  tasks:  #variables from task
#  - name: variables ata task levell
#    vars:
#      NAME: chandu-task
#    ansible.builtin.debug:
#      msg: "Trainer name is {{NAME}}"    #variables from args 
