# we given the same variable name 'NAME' from play,file,prompt,args,task and given the print and checking the which vlue will print

- name: testing vaiable sprecedence
  hosts: mongodb
  vars: #variables from play
    NAME: chandu-play
  vars_files: #variables from file
  - variables.yaml 
  vars_prompt: #variables from prompt
  - name: NAME
    prompt: please enter trainer name
    private: false      
  tasks:  #variables from task
  - name: variables ata task levell
    
    ansible.builtin.debug:
      msg: "Trainer name is {{NAME}}"    #variables from args 

   # 1. first preference is command line args
   # 2. second presedence is task  





   
#- name: testing vaiable sprecedence
#  hosts: mongodb
#  vars: #variables from play
#    NAME: chandu-play
#  vars_files: #variables from file
#  - variables.yaml 
#  vars_prompt: #variables from prompt
#  - name: NAME
#    prompt: please enter trainer name
#    private: false      
#  tasks:  #variables from task
#  - name: variables ata task levell
#    vars:
#      NAME: chandu-task
#    ansible.builtin.debug:
#      msg: "Trainer name is {{NAME}}"    #variables from args 
