- name: simple condition
  hosts: localhost
  vars:
    NAME: Devops
  tasks:
  - name: run this script if name is Devops
    ansible.builtin.debug:
      msg: "{{NAME}}"
    when: NAME == "Devops"     