- name: Install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    # list of string  
    loop:
    - nginx
    - postfix
    - mailx
    - cyrus-sasl-plain