- name: install packages
  hosts: localhost
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    #list of map    
    loop:
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'installed'}
    - {name: 'cyrus-sasl-plain', state: 'absent'}
    - {name: 'mailx', state: 'installed'}